author: mrmag518
description: "An assortment of beneficial features."
main: com.mrmag518.iSafe.iSafe
name: iSafe
load: STARTUP
version: '3.4'
website: http://dev.bukkit.org/server-mods/blockthattnt/
softdepend: [Vault]
commands:
  iSafe:
    description: Main command for iSafe.
    usage: /<command> [argument]
permissions:
  # We do not need to input permissions defaulting to OP, except wildcards.
  # This is because bukkit already does this for us.
  # ------------------------
  iSafe.admin:
    default: op
    children:
      iSafe.bypass.*: true
      iSafe.canceltarget.*: true
      iSafe.use.*: true
      iSafe.forcedrop.*: true
      iSafe.command.*: true
  # ------------------------
  iSafe.bypass.*:
    default: op
    children:
      iSafe.bypass.fullbright: true
      iSafe.bypass.croptrampling: true
      iSafe.bypass.hunger: true
      iSafe.bypass.fish: true
      iSafe.bypass.spamcheck: true
      iSafe.bypass.enchant: true
      iSafe.bypass.blacklist.interact: true
      iSafe.bypass.blacklist.pickup: true
      iSafe.bypass.blacklist.break: true
      iSafe.bypass.blacklist.place: true
      iSafe.bypass.blacklist.drop: true
      iSafe.bypass.blacklist.crafting: true
      iSafe.bypass.teleport: true
      iSafe.bypass.teleport.command: true
      iSafe.bypass.teleport.enderpearl: true
      iSafe.bypass.teleport.plugin: true
      iSafe.bypass.teleport.unknown: true
      iSafe.bypass.teleport.netherportal: true
  # ------------------------
  iSafe.canceltarget.*:
    default: op
    children:
      iSafe.canceltarget.closestplayer: true
      iSafe.canceltarget.custom: true
      iSafe.canceltarget.forgot: true
      iSafe.canceltarget.ownerattacked: true
      iSafe.canceltarget.pigzombie: true
      iSafe.canceltarget.random: true
      iSafe.canceltarget.targetattackedentity: true
      iSafe.canceltarget.targetattackedowner: true
      iSafe.canceltarget.targetdied: true
  # ------------------------
  iSafe.use.*:
    default: op
    children:
      iSafe.use.lavabuckets: true
      iSafe.use.waterbuckets: true
      iSafe.use.bed: true
      iSafe.use.chat: true
      iSafe.use.minecarts: true
      iSafe.use.boats: true
      iSafe.use.fireworks: true
      iSafe.use.potion.invisibility: true
  # ------------------------
  iSafe.forcedrop.*:
    default: true
    children:
      iSafe.forcedrop.glass: true
      iSafe.forcedrop.mobspawner: true
      iSafe.forcedrop.ice: true
      iSafe.forcedrop.bedrock: true
  # ------------------------
  iSafe.command.*:
    default: op
    children:
      iSafe.command.reload: true
      iSafe.command.info: true
      iSafe.command.serverinfo: true
      iSafe.command.resetfile: true
  # ------------------------
  iSafe.bypass.hunger:
    default: true
      